import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { NavbarComponents } from "./components/NavbarComponents";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { faYoutube } from "@fortawesome/free-brands-svg-icons";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* Navbar */}
        <NavbarComponents />

        {/* Main Content */}
        <main>{children}</main>

        {/* Footer */}
        <footer className="col-span-2 bg-white p-4 h-80 text-center content-center">
          <div className="wrapper-footer block">
            <div>Contact Us</div>
            <div>Phone / 02-77471792</div>
            <div>Address / 105406 12F, No.77, Sec. 4, Nanjin E. Rd. Songshan Dist. Taipei</div>
            <div className="mt-2 mb-2">
              <FontAwesomeIcon icon={faYoutube} className="w-8 h-8" />
            </div>
            <div>©2023 Rhyan Taiwan All Rights Reserved.</div>
          </div>
        </footer>
      </body>
    </html>
  );
}
